### ISSUE TITLE
Allow querying of locally stored files from YASQE interface

### ISSUE THREAD

**Issue by RinkeHoekstra** [Data2Semantics/brwsr#18]

**Comment by wouterbeek** [comment]
@RinkeHoekstra Just curious, how would you query a file?

**Comment by RinkeHoekstra** [comment]
brwsr can load local files into an rdflib memory store. This store is then
queried whenever you browse a URI through the web interface. This issue is
about the built-in YASQE interface. Although brwsr does provide a SPARQL
endpoint for this memory store, the YASQE interface does not seem to query
it (or at least, there are no results even when the store clearly contains
matching triples).

So... we're not actually querying a file (literally).

**Comment by RinkeHoekstra** [comment]
This actually works just fine
